letter_vids = {
	'LETTER-A': ['https://media.signbsl.com/videos/asl/youtube/mp4/8RU_xuHOIR0.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26710.mp4',
				 'asl_letter_data/A.mp4'],
	'LETTER-B': ['https://media.signbsl.com/videos/asl/youtube/mp4/od7cHybUp0M.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26711.mp4',
				 'asl_letter_data/B.mp4'],
	'LETTER-C': ['https://media.signbsl.com/videos/asl/youtube/mp4/rqNmaxTWzQA.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26712.mp4',
				 'asl_letter_data/C.mp4'],
	'LETTER-D': ['https://media.signbsl.com/videos/asl/youtube/mp4/sjMYEzrai84.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26713.mp4',
				 'asl_letter_data/D.mp4'],
	'LETTER-E': ['https://media.signbsl.com/videos/asl/youtube/mp4/IWe7tnEwJhA.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26714.mp4',
				 'asl_letter_data/E.mp4'],
	'LETTER-F': ['https://media.signbsl.com/videos/asl/youtube/mp4/NxocGuNyE-Q.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26715.mp4',
				 'asl_letter_data/F.mp4'],
	'LETTER-G': ['https://media.signbsl.com/videos/asl/youtube/mp4/QUIGJ3cO_-g.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26716.mp4',
				 'asl_letter_data/G.mp4'],
	'LETTER-H': ['https://media.signbsl.com/videos/asl/youtube/mp4/kngzzQm3L9U.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26717.mp4',
				 'asl_letter_data/H.mp4'],
	'LETTER-I': ['https://media.signbsl.com/videos/asl/youtube/mp4/gfrWv86jq68.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26718.mp4',
				 'asl_letter_data/I.mp4'],
	'LETTER-J': ['https://media.signbsl.com/videos/asl/youtube/mp4/sNcI-yZSe9c.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26719.mp4',
				 'asl_letter_data/J.mp4'],
	'LETTER-K': ['https://media.signbsl.com/videos/asl/youtube/mp4/xbIJZ5KadVs.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26720.mp4',
				 'asl_letter_data/K.mp4'],
	'LETTER-L': ['https://media.signbsl.com/videos/asl/youtube/mp4/vk3qt-7gOMQ.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26721.mp4',
				 'asl_letter_data/L.mp4'],
	'LETTER-M': ['https://media.signbsl.com/videos/asl/youtube/mp4/YmLHQc-sLbg.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26722.mp4',
				 'asl_letter_data/M.mp4'],
	'LETTER-N': ['https://media.signbsl.com/videos/asl/youtube/mp4/DmaVyqHLe5o.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26723.mp4',
				 'asl_letter_data/N.mp4'],
	'LETTER-O': ['https://media.signbsl.com/videos/asl/youtube/mp4/NnJVE8vCQvE.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26724.mp4',
				 'asl_letter_data/O.mp4'],
	'LETTER-P': ['https://media.signbsl.com/videos/asl/youtube/mp4/ZNBA3a9UMZo.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26725.mp4',
				 'asl_letter_data/P.mp4'],
	'LETTER-Q': ['https://media.signbsl.com/videos/asl/youtube/mp4/3IiQzNRNKrQ.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26726.mp4',
				 'asl_letter_data/Q.mp4'],
	'LETTER-R': ['https://media.signbsl.com/videos/asl/youtube/mp4/5EhyoR9zJU4.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26727.mp4',
				 'asl_letter_data/R.mp4'],
	'LETTER-S': ['https://media.signbsl.com/videos/asl/youtube/mp4/f_dYx5262QA.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26728.mp4',
				 'asl_letter_data/S.mp4'],
	'LETTER-T': ['https://media.signbsl.com/videos/asl/youtube/mp4/D8V-oRC2iXA.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26729.mp4',
				 'asl_letter_data/T.mp4'],
	'LETTER-U': ['https://media.signbsl.com/videos/asl/youtube/mp4/CZz_H9ChUtg.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26730.mp4',
				 'asl_letter_data/U.mp4'],
	'LETTER-V': ['https://media.signbsl.com/videos/asl/youtube/mp4/Tzxdfd9nttk.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26731.mp4',
				 'asl_letter_data/V.mp4'],
	'LETTER-W': ['https://media.signbsl.com/videos/asl/youtube/mp4/jXoFIdkQ4Ho.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26732.mp4',
				 'asl_letter_data/W.mp4'],
	'LETTER-X': ['https://media.signbsl.com/videos/asl/youtube/mp4/uHrqrm1HJx4.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26733.mp4',
				 'asl_letter_data/X.mp4'],
	'LETTER-Y': ['https://media.signbsl.com/videos/asl/youtube/mp4/Oysy99Twx8M.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26734.mp4',
				 'asl_letter_data/Y.mp4'],
	'LETTER-Z': ['https://media.signbsl.com/videos/asl/youtube/mp4/WWggXqJaSg0.mp4',
				 'https://www.signingsavvy.com/media/mp4-ld/26/26735.mp4',
				 'asl_letter_data/Z.mp4']
}
